name: Build Installer and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: List Directory Contents
      shell: pwsh
      run: |
        Write-Host "Current directory: $PWD"
        Write-Host "Directory contents:"
        Get-ChildItem -Recurse | ForEach-Object { Write-Host $_.FullName }
    
    - name: Verify Required Directories
      shell: pwsh
      run: |
        # Check if v1.2.1/Icons and v1.2.1/Logos directories exist
        if (-not (Test-Path "v1.2.1/Icons")) {
          Write-Host "::error::v1.2.1/Icons directory not found. Please make sure it exists in the repository."
          exit 1
        }
        
        if (-not (Test-Path "v1.2.1/Logos")) {
          Write-Host "::error::v1.2.1/Logos directory not found. Please make sure it exists in the repository."
          exit 1
        }
        
        Write-Host "Required directories for icons and logos found."
        Write-Host "Icons directory contents:"
        Get-ChildItem -Path "v1.2.1/Icons" | ForEach-Object { Write-Host "  $_" }
        
        Write-Host "Logos directory contents:"
        Get-ChildItem -Path "v1.2.1/Logos" | ForEach-Object { Write-Host "  $_" }
    
    - name: Check NSIS Installation
      shell: cmd
      run: |
        dir "C:\Program Files (x86)\NSIS"
        
    - name: Build Installer
      shell: cmd
      run: |
        cd installer
        dir
        "C:\Program Files (x86)\NSIS\makensis.exe" SimulanisAutoLogin.nsi
        cd ..
        
    - name: Upload Installer as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SimulanisAutoLogin_Setup
        path: installer/SimulanisAutoLogin_Setup.exe
        retention-days: 5

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: installer/SimulanisAutoLogin_Setup.exe
        name: Release ${{ github.ref_name }}
        body: |
          Simulanis Auto Login Release ${{ github.ref_name }}
          
          This release includes:
          - Installer package for Simulanis Auto Login application
          
          ### Installation
          1. Download the SimulanisAutoLogin_Setup.exe
          2. Run the installer
          3. Follow the installation wizard instructions
        draft: false
        prerelease: false 