name: Build Installer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: List Directory Contents
      run: |
        Write-Host "Current directory: $PWD"
        Write-Host "Directory contents:"
        Get-ChildItem -Recurse | ForEach-Object { Write-Host $_.FullName }
    
    - name: Check NSIS Installation
      shell: cmd
      run: |
        dir "C:\Program Files (x86)\NSIS"
        
    - name: Build Installer
      shell: cmd
      run: |
        cd installer
        dir
        "C:\Program Files (x86)\NSIS\makensis.exe" SimulanisAutoLogin.nsi
        cd ..
        
    - name: Upload Installer
      uses: actions/upload-artifact@v3
      with:
        name: SimulanisAutoLogin_Setup
        path: installer/SimulanisAutoLogin_Setup.exe
        retention-days: 5  # Keep the installer for 5 days 