name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.1

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install NSIS
      run: |
        choco install nsis -y
        refreshenv
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        
    - name: Create Release Directory
      run: |
        $version = "${{ github.ref_name }}"
        mkdir -Force "releases/$version"
        
    - name: Build Installer
      shell: cmd
      run: |
        cd installer
        "C:\Program Files (x86)\NSIS\makensis.exe" SimulanisAutoLogin.nsi
        cd ..
        copy "installer\SimulanisAutoLogin_Setup.exe" "releases\${{ github.ref_name }}\SimulanisAutoLogin_Setup.exe"
        
    - name: Create Build Package
      shell: pwsh
      run: |
        # Set variables
        $version = "${{ github.ref_name }}"
        $buildDir = "releases\$version\build"
        $sourceDir = "$version\SimulanisLogin"
        
        Write-Host "Current directory: $(Get-Location)"
        Write-Host "Source directory: $sourceDir"
        Write-Host "Build directory: $buildDir"
        Write-Host "Available directories:"
        Get-ChildItem -Directory | ForEach-Object { Write-Host $_.FullName }
        
        # Create build directory
        New-Item -Path $buildDir -ItemType Directory -Force
        
        # List contents of version directory
        Write-Host "Contents of $version directory:"
        if (Test-Path $version) {
            Get-ChildItem -Path $version -Recurse | ForEach-Object { Write-Host $_.FullName }
        } else {
            Write-Host "$version directory not found"
        }
        
        # Copy files if source exists
        if (Test-Path $sourceDir) {
            Write-Host "Copying files from $sourceDir to $buildDir"
            
            # Copy files with error handling
            $filesToCopy = @(
                "SimulanisLogin.exe",
                "headless_config.json",
                "Start Simulanis Login (GUI).bat",
                "Start Simulanis Login.bat"
            )
            
            foreach ($file in $filesToCopy) {
                $sourcePath = Join-Path $sourceDir $file
                $destPath = Join-Path $buildDir $file
                if (Test-Path $sourcePath) {
                    Copy-Item -Path $sourcePath -Destination $destPath -Force
                    Write-Host "Copied $file successfully"
                } else {
                    Write-Warning "Source file not found: $sourcePath"
                }
            }
            
            # Copy directories
            $dirsToCopy = @("Icons", "Logos")
            foreach ($dir in $dirsToCopy) {
                $sourcePath = Join-Path $sourceDir $dir
                $destPath = Join-Path $buildDir $dir
                if (Test-Path $sourcePath) {
                    Copy-Item -Path $sourcePath -Destination $destPath -Recurse -Force
                    Write-Host "Copied $dir directory successfully"
                } else {
                    Write-Warning "Source directory not found: $sourcePath"
                }
            }
            
            # Create zip archive
            $zipPath = "releases\$version\Simulanis_Auto_Login_$($version)_Build.zip"
            Write-Host "Creating zip archive at: $zipPath"
            Compress-Archive -Path "$buildDir\*" -DestinationPath $zipPath -Force
            
            # Verify zip creation
            if (Test-Path $zipPath) {
                Write-Host "Zip archive created successfully"
            } else {
                Write-Error "Failed to create zip archive"
                exit 1
            }
            
            # Cleanup build directory
            Remove-Item -Path $buildDir -Recurse -Force
        } else {
            Write-Error "Source directory not found: $sourceDir"
            Write-Host "Current directory contents:"
            Get-ChildItem -Recurse | ForEach-Object { Write-Host $_.FullName }
            exit 1
        }
        
    - name: Create Release Notes
      run: |
        $version = "${{ github.ref_name }}"
        if (-not (Test-Path "releases\$version\RELEASE_NOTES.md")) {
            @"
# Release $version

## What's New
- Updated application with latest features and improvements
- Bug fixes and performance enhancements

## Installation
1. Download the installer (SimulanisAutoLogin_Setup.exe)
2. Run the installer and follow the installation wizard
3. Launch the application from the Start Menu or Desktop shortcut
"@ | Out-File -FilePath "releases\$version\RELEASE_NOTES.md" -Encoding UTF8
        }
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          releases/${{ github.ref_name }}/SimulanisAutoLogin_Setup.exe
          releases/${{ github.ref_name }}/Simulanis_Auto_Login_${{ github.ref_name }}_Build.zip
        body_path: releases/${{ github.ref_name }}/RELEASE_NOTES.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 