name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.1

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install NSIS
      run: |
        choco install nsis -y
        refreshenv
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        
    - name: Create Release Directory
      run: |
        $version = "${{ github.ref_name }}"
        New-Item -Path "releases\$version" -ItemType Directory -Force
        
    - name: Build Installer
      shell: cmd
      run: |
        cd installer
        "C:\Program Files (x86)\NSIS\makensis.exe" SimulanisAutoLogin.nsi
        cd ..
        copy "installer\SimulanisAutoLogin_Setup.exe" "releases\${{ github.ref_name }}\SimulanisAutoLogin_Setup.exe"
        
    - name: Create Release Notes
      run: |
        $version = "${{ github.ref_name }}"
        if (-not (Test-Path "releases\$version\RELEASE_NOTES.md")) {
            @"
# Release $version

## What's New
- Updated application with latest features and improvements
- Bug fixes and performance enhancements

## Installation
1. Download the installer (SimulanisAutoLogin_Setup.exe)
2. Run the installer and follow the installation wizard
3. Launch the application from the Start Menu or Desktop shortcut
"@ | Out-File -FilePath "releases\$version\RELEASE_NOTES.md" -Encoding UTF8
        }
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          releases/${{ github.ref_name }}/SimulanisAutoLogin_Setup.exe
        body_path: releases/${{ github.ref_name }}/RELEASE_NOTES.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 